function(set_common_flags target_name)
	if(MSVC)
		set(common_compile_flags /W3 /WX /utf-8 /permissive- /fp:fast /nologo /EHsc)

		if(UC_ENABLE_IMGUI)
			target_compile_definitions(${target_name} PRIVATE UC_ENABLE_IMGUI=1)
		endif()

		target_compile_options(${target_name} PRIVATE
			$<$<CONFIG:Debug>:${common_compile_flags} /MDd /GR /Zi /Ob0 /Od /RTC1 /D_ITERATOR_DEBUG_LEVEL=2>
			$<$<CONFIG:Release>:${common_compile_flags} /MD /O2 /Ob2 /DNDEBUG>
			$<$<CONFIG:RelWithDebInfo>:${common_compile_flags} /MD /Zi /O2 /Ob1 /DNDEBUG>
			$<$<CONFIG:MinSizeRel>:${common_compile_flags} /MD /O1 /Ob1 /DNDEBUG>
		)

		set(common_link_flags /nologo)

		target_link_options(${target_name} PRIVATE
			$<$<CONFIG:Debug>:${common_link_flags} /debug /INCREMENTAL>
			$<$<CONFIG:Release>:${common_link_flags} /INCREMENTAL:NO>
			$<$<CONFIG:RelWithDebInfo>:${common_link_flags} /debug /INCREMENTAL>
			$<$<CONFIG:MinSizeRel>:${common_link_flags} /INCREMENTAL:NO>
		)
	else()
		message(FATAL_ERROR "set_common_flags compiler not supproted")
	endif()
endfunction()

function(reset_all_flags)
	set(CMAKE_CXX_FLAGS "" CACHE STRING "" FORCE)
	set(CMAKE_C_FLAGS "" CACHE STRING "" FORCE)

	set(CMAKE_CXX_FLAGS_DEBUG "" CACHE STRING "" FORCE)
	set(CMAKE_CXX_FLAGS_RELEASE "" CACHE STRING "" FORCE)
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "" CACHE STRING "" FORCE)
	set(CMAKE_CXX_FLAGS_MINSIZEREL "" CACHE STRING "" FORCE)

	set(CMAKE_C_FLAGS_DEBUG "" CACHE STRING "" FORCE)
	set(CMAKE_C_FLAGS_RELEASE "" CACHE STRING "" FORCE)
	set(CMAKE_C_FLAGS_RELWITHDEBINFO "" CACHE STRING "" FORCE)
	set(CMAKE_C_FLAGS_MINSIZEREL "" CACHE STRING "" FORCE)

	set(CMAKE_EXE_LINKER_FLAGS_DEBUG "" CACHE STRING "" FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_RELEASE "" CACHE STRING "" FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "" CACHE STRING "" FORCE)
	set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "" CACHE STRING "" FORCE)

	set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "" CACHE STRING "" FORCE)
	set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "" CACHE STRING "" FORCE)
	set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "" CACHE STRING "" FORCE)
	set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL "" CACHE STRING "" FORCE)

	set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "" CACHE STRING "" FORCE)
	set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "" CACHE STRING "" FORCE)
	set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "" CACHE STRING "" FORCE)
	set(CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL "" CACHE STRING "" FORCE)
endfunction()

function(print_all_flags)
	message(STATUS "CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG}")
	message(STATUS "CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE}")
	message(STATUS "CMAKE_CXX_FLAGS_RELWITHDEBINFO ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
	message(STATUS "CMAKE_CXX_FLAGS_MINSIZEREL ${CMAKE_CXX_FLAGS_MINSIZEREL}")

	message(STATUS "CMAKE_C_FLAGS_DEBUG ${CMAKE_C_FLAGS_DEBUG}")
	message(STATUS "CMAKE_C_FLAGS_RELEASE ${CMAKE_C_FLAGS_RELEASE}")
	message(STATUS "CMAKE_C_FLAGS_RELWITHDEBINFO ${CMAKE_C_FLAGS_RELWITHDEBINFO}")
	message(STATUS "CMAKE_C_FLAGS_MINSIZEREL ${CMAKE_C_FLAGS_MINSIZEREL}")

	message(STATUS "CMAKE_EXE_LINKER_FLAGS_DEBUG ${CMAKE_EXE_LINKER_FLAGS_DEBUG}")
	message(STATUS "CMAKE_EXE_LINKER_FLAGS_RELEASE ${CMAKE_EXE_LINKER_FLAGS_RELEASE}")
	message(STATUS "CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO ${CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO}")
	message(STATUS "CMAKE_EXE_LINKER_FLAGS_MINSIZEREL ${CMAKE_EXE_LINKER_FLAGS_MINSIZEREL}")

	message(STATUS "CMAKE_SHARED_LINKER_FLAGS_DEBUG ${CMAKE_SHARED_LINKER_FLAGS_DEBUG}")
	message(STATUS "CMAKE_SHARED_LINKER_FLAGS_RELEASE ${CMAKE_SHARED_LINKER_FLAGS_RELEASE}")
	message(STATUS "CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO ${CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO}")
	message(STATUS "CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL ${CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL}")

	message(STATUS "CMAKE_MODULE_LINKER_FLAGS_DEBUG ${CMAKE_MODULE_LINKER_FLAGS_DEBUG}")
	message(STATUS "CMAKE_MODULE_LINKER_FLAGS_RELEASE ${CMAKE_MODULE_LINKER_FLAGS_RELEASE}")
	message(STATUS "CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO ${CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO}")
	message(STATUS "CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL ${CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL}")

endfunction()
